/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    franchises: Franchise;
    players: Player;
    auctions: Auction;
    bids: Bid;
    trades: Trade;
    tournaments: Tournament;
    matches: Match;
    awards: Award;
    activity: Activity;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    franchises: FranchisesSelect<false> | FranchisesSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    auctions: AuctionsSelect<false> | AuctionsSelect<true>;
    bids: BidsSelect<false> | BidsSelect<true>;
    trades: TradesSelect<false> | TradesSelect<true>;
    tournaments: TournamentsSelect<false> | TournamentsSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    activity: ActivitySelect<false> | ActivitySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'league-settings': LeagueSetting;
  };
  globalsSelect: {
    'league-settings': LeagueSettingsSelect<false> | LeagueSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'commissioner' | 'owner';
  /**
   * The team this owner controls.
   */
  franchise?: (number | null) | Franchise;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franchises".
 */
export interface Franchise {
  id: number;
  name: string;
  /**
   * URL handle, e.g. "dais-dynasty"
   */
  slug?: string | null;
  logo?: (number | null) | Media;
  /**
   * Team accent (hex).
   */
  color?: string | null;
  bio?: string | null;
  /**
   * Display name of the franchise owner (shown in standings & tournaments).
   */
  ownerName?: string | null;
  /**
   * Optional linked user account.
   */
  owner?: (number | null) | User;
  /**
   * Total budget for the auction.
   */
  purseTotal?: number | null;
  /**
   * Maintained automatically as players are won.
   */
  purseSpent?: number | null;
  /**
   * Season founded.
   */
  established?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  /**
   * CSV rank
   */
  rank?: number | null;
  name: string;
  position: 'PG' | 'SG' | 'SF' | 'PF' | 'C';
  /**
   * Overall rating
   */
  ovr: number;
  category?: ('All-Time Legend' | 'Current' | 'All-Decade' | 'All-Star' | 'Current + All-Time') | null;
  nbaTeam?: string | null;
  photo?: (number | null) | Media;
  /**
   * Starting auction price.
   */
  basePrice?: number | null;
  status?: ('available' | 'sold' | 'unsold' | 'released') | null;
  /**
   * Current owning team (if sold).
   */
  franchise?: (number | null) | Franchise;
  /**
   * Final hammer price.
   */
  soldPrice?: number | null;
  /**
   * Kept by its team for a main auction (set during retention).
   */
  retained?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auctions".
 */
export interface Auction {
  id: number;
  title: string;
  /**
   * Main = league reset (retain 3, rest pooled). Mid = auction the free-agent pool.
   */
  kind?: ('main' | 'mid') | null;
  status?: ('scheduled' | 'live' | 'ended') | null;
  /**
   * Retention window is open (main only).
   */
  retentionOpen?: boolean | null;
  /**
   * Players each team keeps.
   */
  retentionLimit?: number | null;
  /**
   * Target cutoff for retentions.
   */
  retentionDeadline?: string | null;
  /**
   * Max players per team.
   */
  squadCap?: number | null;
  /**
   * Minimum raise.
   */
  minIncrement?: number | null;
  /**
   * Countdown per lot.
   */
  timerSeconds?: number | null;
  /**
   * Player currently on the block.
   */
  currentPlayer?: (number | null) | Player;
  lotStatus?: ('idle' | 'open' | 'going1' | 'going2' | 'sold' | 'unsold') | null;
  currentHighBid?: number | null;
  currentHighFranchise?: (number | null) | Franchise;
  /**
   * When the current lot countdown ends.
   */
  timerEndsAt?: string | null;
  /**
   * Ordered list of players to auction.
   */
  queue?: (number | Player)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bids".
 */
export interface Bid {
  id: number;
  auction: number | Auction;
  amount: number;
  franchise: number | Franchise;
  player?: (number | null) | Player;
  bidder?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trades".
 */
export interface Trade {
  id: number;
  fromFranchise: number | Franchise;
  toFranchise: number | Franchise;
  /**
   * Players the proposer gives up (max 3).
   */
  offeredPlayers?: (number | Player)[] | null;
  /**
   * Players the proposer wants (max 3).
   */
  requestedPlayers?: (number | Player)[] | null;
  /**
   * Currency from → to (negative = the other way).
   */
  cashAdjustment?: number | null;
  note?: string | null;
  status?: ('proposed' | 'countered' | 'accepted' | 'rejected' | 'vetoed' | 'expired') | null;
  /**
   * Accept-by deadline — auto-expires the offer if not settled (max 3 months out).
   */
  expiresAt?: string | null;
  /**
   * Loan start — set when the trade is accepted. Players move to the other team.
   */
  startsAt?: string | null;
  /**
   * Loan end — players revert to their original teams once this passes.
   */
  endsAt?: string | null;
  proposedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments".
 */
export interface Tournament {
  id: number;
  name: string;
  format?: ('round-robin' | 'single-elim' | 'double-elim' | 'groups-knockout' | 'season-league') | null;
  status?: ('upcoming' | 'in-progress' | 'completed') | null;
  /**
   * e.g. "Season 1"
   */
  season?: string | null;
  participants?: (number | Franchise)[] | null;
  description?: string | null;
  champion?: (number | null) | Franchise;
  /**
   * Auto-generated bracket/fixture structure.
   */
  bracket?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  tournament?: (number | null) | Tournament;
  /**
   * e.g. "Quarterfinal"
   */
  round?: string | null;
  status?: ('scheduled' | 'live' | 'final') | null;
  homeFranchise: number | Franchise;
  homeScore?: number | null;
  awayScore?: number | null;
  awayFranchise: number | Franchise;
  /**
   * Match awarded by walkover (no game played).
   */
  walkover?: boolean | null;
  /**
   * e.g. [[28,24],[19,30],...] home/away per quarter.
   */
  quarterScores?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Player of the match.
   */
  mvp?: (number | null) | Player;
  playedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  title: string;
  type?: ('champion' | 'mvp' | 'dpoy' | 'mip' | 'goat-owner' | 'other') | null;
  season?: string | null;
  franchise?: (number | null) | Franchise;
  player?: (number | null) | Player;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity".
 */
export interface Activity {
  id: number;
  type?: ('auction' | 'trade' | 'match' | 'award' | 'system') | null;
  message: string;
  franchise?: (number | null) | Franchise;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'franchises';
        value: number | Franchise;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'auctions';
        value: number | Auction;
      } | null)
    | ({
        relationTo: 'bids';
        value: number | Bid;
      } | null)
    | ({
        relationTo: 'trades';
        value: number | Trade;
      } | null)
    | ({
        relationTo: 'tournaments';
        value: number | Tournament;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'activity';
        value: number | Activity;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  franchise?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franchises_select".
 */
export interface FranchisesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  color?: T;
  bio?: T;
  ownerName?: T;
  owner?: T;
  purseTotal?: T;
  purseSpent?: T;
  established?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  rank?: T;
  name?: T;
  position?: T;
  ovr?: T;
  category?: T;
  nbaTeam?: T;
  photo?: T;
  basePrice?: T;
  status?: T;
  franchise?: T;
  soldPrice?: T;
  retained?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auctions_select".
 */
export interface AuctionsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  status?: T;
  retentionOpen?: T;
  retentionLimit?: T;
  retentionDeadline?: T;
  squadCap?: T;
  minIncrement?: T;
  timerSeconds?: T;
  currentPlayer?: T;
  lotStatus?: T;
  currentHighBid?: T;
  currentHighFranchise?: T;
  timerEndsAt?: T;
  queue?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bids_select".
 */
export interface BidsSelect<T extends boolean = true> {
  auction?: T;
  amount?: T;
  franchise?: T;
  player?: T;
  bidder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trades_select".
 */
export interface TradesSelect<T extends boolean = true> {
  fromFranchise?: T;
  toFranchise?: T;
  offeredPlayers?: T;
  requestedPlayers?: T;
  cashAdjustment?: T;
  note?: T;
  status?: T;
  expiresAt?: T;
  startsAt?: T;
  endsAt?: T;
  proposedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments_select".
 */
export interface TournamentsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  status?: T;
  season?: T;
  participants?: T;
  description?: T;
  champion?: T;
  bracket?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  tournament?: T;
  round?: T;
  status?: T;
  homeFranchise?: T;
  homeScore?: T;
  awayScore?: T;
  awayFranchise?: T;
  walkover?: T;
  quarterScores?: T;
  mvp?: T;
  playedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  season?: T;
  franchise?: T;
  player?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_select".
 */
export interface ActivitySelect<T extends boolean = true> {
  type?: T;
  message?: T;
  franchise?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "league-settings".
 */
export interface LeagueSetting {
  id: number;
  seasonName?: string | null;
  leagueLogo?: (number | null) | Media;
  /**
   * e.g. "Dollars", "Credits".
   */
  currencyName?: string | null;
  /**
   * Prefix, e.g. "$".
   */
  currencySymbol?: string | null;
  /**
   * Suffix, e.g. "M" for millions.
   */
  currencySuffix?: string | null;
  defaultPurse?: number | null;
  squadCap?: number | null;
  transferWindowOpen?: string | null;
  transferWindowClose?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "league-settings_select".
 */
export interface LeagueSettingsSelect<T extends boolean = true> {
  seasonName?: T;
  leagueLogo?: T;
  currencyName?: T;
  currencySymbol?: T;
  currencySuffix?: T;
  defaultPurse?: T;
  squadCap?: T;
  transferWindowOpen?: T;
  transferWindowClose?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}